name: Android CI

on:   
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make Gradle executable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build

  test:

    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
  
  detekt:
    
    name: Run Detekt Checkstyle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Detekt Checkstyle
        run: ./gradlew detekt

  deploy:

    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: [build, test, detekt]
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build Release
        run: ./gradlew assembleRelease
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.1.1
        with:
          appId: ${{weatherapp-96278}}
          token: ${{1//0ctnjDXZa7SaYCgYIARAAGAwSNwF-L9IrKHXY2O1_qa9Ivj0MiO2GQhfn3i2vFO9-Gtbub2WpmXVJmXEjhe5jTWPC3EKBJd_faY0}}
          groups: testers
          file: app/build/outputs/apk/release/app-release-unsigned.apk

